// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.Data;

#nullable disable

namespace Proyecto_Final.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "García Márquez",
                            FechaNacimiento = new DateTime(1927, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Colombiana",
                            Nombre = "Gabriel"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Vargas Llosa",
                            FechaNacimiento = new DateTime(1936, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Peruana",
                            Nombre = "Mario"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Allende",
                            FechaNacimiento = new DateTime(1942, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Chilena",
                            Nombre = "Isabel"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Borges",
                            FechaNacimiento = new DateTime(1899, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Argentina",
                            Nombre = "Jorge Luis"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Fuentes",
                            FechaNacimiento = new DateTime(1928, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Mexicana",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id = 6,
                            Apellidos = "Paz",
                            FechaNacimiento = new DateTime(1914, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Mexicana",
                            Nombre = "Octavio"
                        },
                        new
                        {
                            Id = 7,
                            Apellidos = "Esquivel",
                            FechaNacimiento = new DateTime(1950, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Mexicana",
                            Nombre = "Laura"
                        },
                        new
                        {
                            Id = 8,
                            Apellidos = "Neruda",
                            FechaNacimiento = new DateTime(1904, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Chilena",
                            Nombre = "Pablo"
                        },
                        new
                        {
                            Id = 9,
                            Apellidos = "de Cervantes",
                            FechaNacimiento = new DateTime(1547, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Española",
                            Nombre = "Miguel"
                        },
                        new
                        {
                            Id = 10,
                            Apellidos = "García Lorca",
                            FechaNacimiento = new DateTime(1898, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nacionalidad = "Española",
                            Nombre = "Federico"
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Novela"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Poesía"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ensayo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cuento"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Teatro"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Historia"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Biografía"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ciencia ficción"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Misterio"
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPaginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            FechaPublicacion = new DateTime(1967, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 417,
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 2,
                            FechaPublicacion = new DateTime(1963, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 350,
                            Titulo = "La ciudad y los perros"
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 3,
                            FechaPublicacion = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 490,
                            Titulo = "La casa de los espíritus"
                        },
                        new
                        {
                            Id = 4,
                            AutorId = 4,
                            FechaPublicacion = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 4,
                            NumeroPaginas = 180,
                            Titulo = "El Aleph"
                        },
                        new
                        {
                            Id = 5,
                            AutorId = 5,
                            FechaPublicacion = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 300,
                            Titulo = "La región más transparente"
                        },
                        new
                        {
                            Id = 6,
                            AutorId = 6,
                            FechaPublicacion = new DateTime(1950, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 3,
                            NumeroPaginas = 250,
                            Titulo = "El laberinto de la soledad"
                        },
                        new
                        {
                            Id = 7,
                            AutorId = 7,
                            FechaPublicacion = new DateTime(1989, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 250,
                            Titulo = "Como agua para chocolate"
                        },
                        new
                        {
                            Id = 8,
                            AutorId = 8,
                            FechaPublicacion = new DateTime(1924, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            NumeroPaginas = 100,
                            Titulo = "Veinte poemas de amor"
                        },
                        new
                        {
                            Id = 9,
                            AutorId = 9,
                            FechaPublicacion = new DateTime(1605, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            NumeroPaginas = 863,
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 10,
                            AutorId = 10,
                            FechaPublicacion = new DateTime(1928, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            NumeroPaginas = 150,
                            Titulo = "Romancero gitano"
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucionEfectiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentarios = "Primer préstamo",
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 6,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 7,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 7,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 8,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 8,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 9,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 9,
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 10,
                            Estado = "Pendiente",
                            FechaDevolucion = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPrestamo = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibroId = 10,
                            UsuarioId = 10
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Ramírez",
                            Cedula = "10101010",
                            Direccion = "San José",
                            Email = "ana@test.com",
                            FechaNacimiento = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Telefono = "8888-1111"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gómez",
                            Cedula = "20202020",
                            Direccion = "Alajuela",
                            Email = "luis@test.com",
                            FechaNacimiento = new DateTime(1985, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            Telefono = "8888-2222"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Fernández",
                            Cedula = "30303030",
                            Direccion = "Heredia",
                            Email = "maria@test.com",
                            FechaNacimiento = new DateTime(1992, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Telefono = "8888-3333"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Solís",
                            Cedula = "40404040",
                            Direccion = "Cartago",
                            Email = "pedro@test.com",
                            FechaNacimiento = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Telefono = "8888-4444"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Jiménez",
                            Cedula = "50505050",
                            Direccion = "Puntarenas",
                            Email = "sofia@test.com",
                            FechaNacimiento = new DateTime(1995, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofía",
                            Telefono = "8888-5555"
                        },
                        new
                        {
                            Id = 6,
                            Apellidos = "Vega",
                            Cedula = "60606060",
                            Direccion = "Limón",
                            Email = "carlos@test.com",
                            FechaNacimiento = new DateTime(1983, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Telefono = "8888-6666"
                        },
                        new
                        {
                            Id = 7,
                            Apellidos = "Castro",
                            Cedula = "70707070",
                            Direccion = "San Carlos",
                            Email = "elena@test.com",
                            FechaNacimiento = new DateTime(1991, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Elena",
                            Telefono = "8888-7777"
                        },
                        new
                        {
                            Id = 8,
                            Apellidos = "Martínez",
                            Cedula = "80808080",
                            Direccion = "Liberia",
                            Email = "jose@test.com",
                            FechaNacimiento = new DateTime(1987, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "José",
                            Telefono = "8888-8888"
                        },
                        new
                        {
                            Id = 9,
                            Apellidos = "Rojas",
                            Cedula = "90909090",
                            Direccion = "Nicoya",
                            Email = "lucia@test.com",
                            FechaNacimiento = new DateTime(1993, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lucía",
                            Telefono = "8888-9999"
                        },
                        new
                        {
                            Id = 10,
                            Apellidos = "Hernández",
                            Cedula = "10111212",
                            Direccion = "Quepos",
                            Email = "miguel@test.com",
                            FechaNacimiento = new DateTime(1989, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel",
                            Telefono = "8888-0000"
                        });
                });

            modelBuilder.Entity("Proyecto_Final.Models.Libro", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Genero", "Genero")
                        .WithMany("Libros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Prestamo", b =>
                {
                    b.HasOne("Proyecto_Final.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Final.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Genero", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Proyecto_Final.Models.Usuario", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
